### ISSUE TITLE
大佬你好，找不到application.yaml这个文件

### ISSUE THREAD

**Issue by 13145678618** [c-ttpfx/chatgpt-java-wx#1]

**Comment by c-ttpfx** [comment]
不就在resource目录下的吗
![image](https://user-images.githubusercontent.com/101882388/229543256-04ba6168-1dc2-4162-a617-ae603c0c784e.png)

**Comment by 13145678618** [comment]
> 不就在资源目录下的吗 ![图像](https://user-images.githubusercontent.com/101882388/229543256-04ba6168-1dc2-4162-a617-ae603c0c784e.png)
谢谢大佬，可以请教下登录页面可以删除吗，我在微信开发者工具里面输入数据库用户名和密码没反应

**Comment by c-ttpfx** [comment]
不好删除，因为我在所有页面里面都加入了身份验证，如果不合法，那么就会重定向到登录页面。

你点登录没有反应，可以看看请求有没有发出去，还有就是要把微信开发者工具的https校验关掉

![image](https://user-images.githubusercontent.com/101882388/229553104-0bd5d0ba-d290-4c46-aeda-d2ba93b997b0.png)

![image](https://user-images.githubusercontent.com/101882388/229552837-a1bf1b62-d8fd-4f2c-9587-d98f2a63a308.png)

**Comment by 13145678618** [comment]
> 不好删除，因为我在所有页面里面都加入了身份验证，如果不合法，那么就会重定向到登录页面。
> 
> 你点登录没有反应，可以看看请求有没有发出去，还有就是要把微信开发者工具的https校验关掉
> 
> ![image](https://user-images.githubusercontent.com/101882388/229553505-e84efd56-04f9-4854-813e-ebf1f472785c.png)
> 
> ![image](https://user-images.githubusercontent.com/101882388/229552837-a1bf1b62-d8fd-4f2c-9587-d98f2a63a308.png)

谢谢大佬，请求这样好像是没发出去，估计是我哪里配置有问题，

**Comment by 13145678618** [comment]
> > 不好删除，因为我在所有页面里面都加入了身份验证，如果不合法，那么就会重定向到登录页面。
> > 你点登录没有反应，可以看看请求有没有发出去，还有就是要把微信开发者工具的https校验关掉
> > ![image](https://user-images.githubusercontent.com/101882388/229553505-e84efd56-04f9-4854-813e-ebf1f472785c.png)
> > ![image](https://user-images.githubusercontent.com/101882388/229552837-a1bf1b62-d8fd-4f2c-9587-d98f2a63a308.png)
> 
> 谢谢大佬，请求这样好像是没发出去，估计是我哪里配置有问题，

- /
![ttpfx的聊天机器人 - 微信开发者工具 Stable v1 06 2303060 2023_4_3 23_54_18](https://user-images.githubusercontent.com/128766292/229564076-10aefaa8-5a0f-48b7-91e1-9ccbc453a680.png)
大佬显示这个是没配置好服务器吗

**Comment by c-ttpfx** [comment]
它不是报404了吗，就代表你服务器的地址写错了，或者服务器没有打开
