### ISSUE TITLE
为什么test是failed

### ISSUE THREAD

**Issue by DreamMemory001** [c-ttpfx/chatgpt-java-wx#2]
我本地想先测试一下server端的代码，本地是没问题可以翻墙的，但是为什么一直显示failed，我后来加了代理也不行，为什么啊？

**Comment by c-ttpfx** [comment]
本地测试换个稳定点的vpn吧，我这边使用clash for windows也是不行的

**Comment by DreamMemory001** [comment]
你好，我这边用的是pigcha，我测试谷歌也是没问题的呢
![image](https://user-images.githubusercontent.com/32425458/236667614-037c08c8-9d3e-4cc5-87e0-23a7477351cd.png)
![image](https://user-images.githubusercontent.com/32425458/236667671-db42a039-db9c-4d78-9973-3c5869e3ece9.png)
但是就是一直是failed，也是很奇怪，key我也换了一次，应该都没问题的呢

**Comment by DreamMemory001** [comment]
我也更换了一些节点，确认网络是可以访问chatgpt的，所以您认为还可能是什么原因呢？麻烦啦，谢谢

**Comment by c-ttpfx** [comment]
你这个应该不是网络的问题了，你可以把错误的堆栈信息给出吗，去代码里面加一条打印语句或者debug一下

**Comment by c-ttpfx** [comment]
网络问题是报这个错误

![image](https://user-images.githubusercontent.com/101882388/236668538-0a861387-c862-4892-8770-16eddc440966.png)

**Comment by DreamMemory001** [comment]
![image](https://user-images.githubusercontent.com/32425458/236668649-e2bead18-aec5-4ca3-83ef-0eed7edb1d6a.png)
你好，应该是网络问题，就是有时候也是会出现这个的报错

**Comment by c-ttpfx** [comment]
我这边换了个稳定的vpn是可以正常使用的，你那边出现问题可以检查下maven导包是否成功了和网络能否ping通openai

![image](https://user-images.githubusercontent.com/101882388/236668995-887b701f-25a5-4a1e-95ac-8dab0a4050d9.png)

**Comment by DreamMemory001** [comment]
![image](https://user-images.githubusercontent.com/32425458/236669700-23bf904c-21f9-4d88-9e7a-0d45a1c5b436.png)
![image](https://user-images.githubusercontent.com/32425458/236669722-5cd2bf96-0d9c-403c-9b03-6d72d9c7353e.png)
你好，就是ping现在也没问题，maven也没问题，但是依然是failed，就真的很奇怪

**Comment by c-ttpfx** [comment]
没有报错的堆栈信息那我也不知道是什么原因了

**Comment by DreamMemory001** [comment]
是不是你的测试程序和您上传github1的不一样啊！？
![image](https://user-images.githubusercontent.com/32425458/236672195-75e82c7b-576b-4af3-abfe-d46abdb2c23f.png)

**Comment by DreamMemory001** [comment]
![image](https://user-images.githubusercontent.com/32425458/236672487-e3c11ca9-be8c-4c34-801c-3d53ebd40d25.png)
![image](https://user-images.githubusercontent.com/32425458/236672489-de7414b2-526d-4bf0-81d5-e0a29394ded5.png)
这是debug的结果

**Comment by c-ttpfx** [comment]
> 

刚clone下来的，可以正常运行

![image](https://user-images.githubusercontent.com/101882388/236672968-2409a7ca-c9fa-458d-8bba-eb049d0eb4e1.png)

![image](https://user-images.githubusercontent.com/101882388/236672957-b3b47399-58c1-49ab-8dfa-dbb133123fb7.png)

**Comment by c-ttpfx** [comment]
> ![image](https://user-images.githubusercontent.com/32425458/236672487-e3c11ca9-be8c-4c34-801c-3d53ebd40d25.png) ![image](https://user-images.githubusercontent.com/32425458/236672489-de7414b2-526d-4bf0-81d5-e0a29394ded5.png) 这是debug的结果

这个应该是你环境的原因，有几个地方可以检查下

- 项目的JDK是否为8
- maven里面的依赖是否全部导入成功
- 网络问题

**Comment by c-ttpfx** [comment]
> > 我这边换了个稳定的vpn是可以正常使用的，你那边出现问题可以检查下maven导包是否成功了和网络能否ping通openai
> > ![image](https://user-images.githubusercontent.com/101882388/236668995-887b701f-25a5-4a1e-95ac-8dab0a4050d9.png)
> 
> 大佬问一个无关的问题，你的idea是什么版本或者什么主题，看着真舒服

版本2023.1，装了一个one dark theme插件，主题是One Dark Vivid Italic，然后再放了一张背景图片

**Comment by c-ttpfx** [comment]
代码已经重构，现在支持代理了，基本不会出现网络无法访问的情况了
